### ISSUE TITLE
data filename must not end in .json (+ security)

### ISSUE THREAD

**Issue by andreineculau** [jessedc/ajv-cli#13]
you make use of nodejs' require, presumably for the sake of omit-extension convenience, but this means that ajv-cli cannot be use to validate an AWS Cloudformation `*.template` instance, or `.eslintrc`, etc i.e. files that are JSON formatted, but don't end in `.json`

PS: also, using nodejs' require, is major security issue imho. I build some service to validate JSON, someone passes down a js module instead, that does evil things, but still exports a JSON instance. Everything works fine still, but the system has been tempered with.

**Comment by epoberezkin** [comment]
There was PR #12 (that was closed as it needed improvement) that was addressing this issue by allowing extensions other than .json

General use case for CLI is validating files that you control and `require` is used on purpose to allow .js files (schema / data can be the result of several statements, also to allow comments). For files that you control security is not an issue.

If you are validating data from some external source you are more likely to use ajv in code rather than as cli; even if you use cli you can use some simple script to sanitise json.

**Comment by epoberezkin** [comment]
closed by #14
