### ISSUE TITLE
Default schema and data files

### ISSUE THREAD

**Issue by tejasbubane** [jessedc/ajv-cli#24]
This recently came up in [discussion](https://github.com/exercism/x-common/issues/700#issuecomment-285934566) in the exercism repo.

CLI should be able to auto-detect source and data files with some standard name in case no arguments are passed. Maybe `schema.json` and `data.json`?
This way if I have these two files, I can just run `ajv` directly. If filenames are different than default, I shall pass them as arguments to `-s` and `-d`.

**Comment by epoberezkin** [comment]
@tejasbubane Not sure I like this idea, it doesn't seem to me to have much value. If you need to support default names in your app/library it's very simple to do with a wrapper script, and different users may need different default names.

**Comment by tejasbubane** [comment]
Agreed. Even I don't feel this adds much value, but since this came up in the discussion, I thought I should bring it to notice here. Keeping this open if @kotp has any more suggestions.

**Comment by kotp** [comment]
It is not that there are default file names such as schema.json, but when you have a project with more than one schema.

some_purpose.schema.json will match some_purpose.json file... the schema can then be matched for that purpose.

This can of course, since there is a pattern, be done as a shell function.  There are some client files that do this, it appears, or perhaps it is facilitated as part of an IDE plugin.  I have not yet investigated to know where the functionality is coming from, I only know in that project, the pattern is not in place... hence the suggestion that we put it in place (in the other project).

**Comment by tejasbubane** [comment]
> hence the suggestion that we put it in place (in the other project).

Ahh I misinterpreted your comment there @kotp. I guess this issue can be closed then.
